<!doctype html><html><head><meta charset="utf-8"><style>
@page{margin:28px}body{font-family:DejaVu Sans,sans-serif;color:#1f2937;font-size:10px}.header{width:100%;margin-bottom:22px}.logo{width:145px}.title{text-align:right;font-size:25px;color:#007dc5;font-weight:bold}.grid{width:100%;margin-bottom:18px}.grid td{width:50%;vertical-align:top}.label{color:#6b7280;font-size:8px;text-transform:uppercase;letter-spacing:.5px}table.items{width:100%;border-collapse:collapse}.items th{background:#007dc5;color:white;padding:7px 5px;text-align:left;font-size:8px}.items td{padding:7px 5px;border-bottom:1px solid #e5e7eb}.right{text-align:right}.totals{margin-left:auto;margin-top:16px;width:260px}.totals td{padding:6px}.total{font-size:14px;font-weight:bold;border-top:2px solid #007dc5}.footer{position:fixed;bottom:0;color:#6b7280;font-size:8px}
</style></head><body>
<table class="header"><tr><td><img class="logo" src="{{ $logo }}"></td><td class="title">INVOICE</td></tr></table>
<table class="grid"><tr><td><div class="label">Issued by</div><strong>Bowido</strong><br>{{ config('invoice.company_address') }}<br>{{ config('invoice.company_email') }}</td><td><div class="label">Customer</div><strong>{{ $details?->company_name ?? $customer?->name }}</strong><br>{{ $details?->street ?? $details?->billing_address }}<br>{{ $details?->postal_code }} {{ $details?->country }}<br>{{ $details?->billing_email ?? $customer?->email }}<br>KvK: {{ $details?->kvk ?? '—' }}</td></tr></table>
<table class="grid"><tr><td><span class="label">Invoice number</span><br><strong>{{ $invoice->invoice_number }}</strong></td><td><span class="label">Invoice date / period</span><br>{{ optional($invoice->issued_at)->format('d-m-Y') }} · {{ $invoice->period_start->format('d-m-Y') }} – {{ $invoice->period_end->format('d-m-Y') }}</td></tr></table>
<table class="items"><thead><tr><th>Received</th><th>Pallet</th><th class="right">Grace</th><th class="right">Overdue</th><th class="right">Price/day</th><th class="right">Total</th></tr></thead><tbody>
@forelse($invoice->items as $item)<tr><td>{{ $item->metadata['received_date'] ?? $item->period_start->format('d-m-Y') }}</td><td>{{ $item->pallet?->pallet_name ?? $item->pallet?->reference_code ?? $item->pallet?->qr_code ?? $item->description }}</td><td class="right">{{ $item->metadata['grace_period_days'] ?? 0 }}</td><td class="right">{{ $item->billed_days }}</td><td class="right">{{ number_format((float)$item->price_per_day,2,',','.') }} {{ $invoice->currency }}</td><td class="right">{{ number_format((float)$item->amount,2,',','.') }} {{ $invoice->currency }}</td></tr>@empty<tr><td colspan="6">No billable pallet charges for this period.</td></tr>@endforelse
</tbody></table><table class="totals"><tr><td>Subtotal</td><td class="right">{{ number_format((float)$invoice->subtotal_amount,2,',','.') }} {{ $invoice->currency }}</td></tr><tr class="total"><td>Total</td><td class="right">{{ number_format((float)$invoice->total_amount,2,',','.') }} {{ $invoice->currency }}</td></tr></table>
<div class="footer">Bowido · Generated securely with TrackPal</div></body></html>
